name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run linter
        id: linter
        working-directory: ./frontend
        run: npm run lint

      - name: Check linter result
        run: |
          if [ ${{ steps.linter.outcome }} != 'success' ]; then
            echo "Linting failed. Cannot merge this PR."
            exit 1
          fi
